document.write('<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="550" height="300">');
document.write('<param name="movie" value="slideshow.swf">');
document.write('<param name="WMODE" value="transparent">');
document.write('<param name="PLAY" value="true">');
document.write('<param name="LOOP" value="false">');
document.write('<param name="QUALITY" value="high">');
document.write('<param name="MENU" value="false">');
document.write('<embed src="slideshow.swf" wmode="transparent" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash"  width="550" height="300" quality="high">');
document.write('</embed>');
document.write('</object>');
