var imagen = 0; imageObj = new Image(); imagenes = new Array(); imagenes[0]="website_design_imagery/website_development_samples/web_design_sample_1.gif"; imagenes[1]="website_design_imagery/website_development_samples/website_development_sample_2.gif"; imagenes[2]="website_design_imagery/website_development_samples/web_design_sample_3.gif"; imagenes[3]="website_design_imagery/website_development_samples/website_development_sample_4.gif"; imagenes[4]="website_design_imagery/website_development_samples/web_design_sample_5.gif"; imagenes[5]="website_design_imagery/website_development_samples/website_development_sample_6.gif"; imagenes[6]="website_design_imagery/website_development_samples/web_design_sample_7.gif";
for(imagen=0; imagen<=3; imagen++) { imageObj.src=imagenes[imagen]; }
var secs; var timerID = null; var timerRunning = false; var delay = 50;
function InitializeHomeTransients() { secs = 0; StopTheClock(); StartTheTimer(); }
function StopTheClock() { if(timerRunning) { clearTimeout(timerID); timerRunning = false; } }
function StartTheTimer() { if (secs==7) { blendimage('blenddiv1','blendimage1',imagenes[0],1500); } if (secs==8) { blendimage('blenddiv2','blendimage2',imagenes[1],1500); } if (secs==9) { blendimage('blenddiv3','blendimage3',imagenes[2],1500); } if (secs==10) { blendimage('blenddiv4','blendimage4',imagenes[3],1500); } if (secs==11) { blendimage('blenddiv5','blendimage5',imagenes[4],1500); } if (secs==12) { blendimage('blenddiv6','blendimage6',imagenes[5],1500); } if (secs==13) { blendimage('blenddiv7','blendimage7',imagenes[6],1500); } if (secs == 14) { StopTheClock(); } else { secs = secs + 1; timerRunning = true; timerID = self.setTimeout("StartTheTimer()", delay); } }
function opacity(id, opacStart, opacEnd, millisec) { var speed = Math.round(millisec / 100); var timer = 0; if(opacStart > opacEnd) { for(i = opacStart; i >= opacEnd; i--) { setTimeout("changeOpac(" + i + ",'" + id + "')",(timer * speed)); timer++; } } else if(opacStart < opacEnd) { for(i = opacStart; i <= opacEnd; i++) { setTimeout("changeOpac(" + i + ",'" + id + "')",(timer * speed)); timer++; } } }
function changeOpac(opacity, id) { var object = document.getElementById(id).style; object.opacity = (opacity / 100); object.MozOpacity = (opacity / 100); object.KhtmlOpacity = (opacity / 100); object.filter = "alpha(opacity=" + opacity + ")"; }
function shiftOpacity(id, millisec) { if(document.getElementById(id).style.opacity == 0) { opacity(id, 0, 100, millisec); } else { opacity(id, 100, 0, millisec); } }
function blendimage(divid, imageid, imagefile, millisec) { var speed = Math.round(millisec / 100); var timer = 0; document.getElementById(divid).style.backgroundImage = "url(" + document.getElementById(imageid).src + ")"; changeOpac(0, imageid); document.getElementById(imageid).src = imagefile; for(i = 0; i <= 80; i++) { setTimeout("changeOpac(" + i + ",'" + imageid + "')",(timer * speed)); timer++; } }
function currentOpac(id, opacEnd, millisec) { var currentOpac = 100; if(document.getElementById(id).style.opacity < 100) { currentOpac = document.getElementById(id).style.opacity * 100; } opacity(id, currentOpac, opacEnd, millisec); }