var TREE1_NODES = [
	['Associate Roster', null, null,
              ['Executives', null, null,
                  ['CoolControls', httpwww.cooldev.comcoolcontrols.html, null],
                  ['CoolMenus PRO', httpwww.cooldev.comcoolmenuspro.html, null],
                  ['CoolMenus', httpwww.cooldev.comcoolmenus.html, null],
              ],
              ['Managers', null, null,
                  ['KoolSockets', httpwww.cooldev.comkoolsockets.html, null],
                  ['KoolStorage', httpwww.cooldev.comkoolstorage.html, null],
              ],
              ['Loan Processing', null, null,
                  ['StarBurn SDK', httpwww.cooldev.comcdrwlib.html, null],
              ],
              ['Loan Officers', null, null,
                  ['InternetAUDIT', httpwww.cooldev.comia.html, null],
                  ['CoolDocumenter', httpwww.cooldev.comapplications.html, null],
              ],
              ['Loan Floor', null, null,
                  ['InternetAUDIT', httpwww.cooldev.comia.html, null],
                  ['CoolDocumenter', httpwww.cooldev.comapplications.html, null],
			  ],
              ['By Team', null, null,
                  ['InternetAUDIT', httpwww.cooldev.comia.html, null],
                  ['CoolDocumenter', httpwww.cooldev.comapplications.html, null],
			  ],
              ['Administrators', null, null,
                  ['InternetAUDIT', httpwww.cooldev.comia.html, null],
                  ['CoolDocumenter', httpwww.cooldev.comapplications.html, null],
			  ],
   	      ['Pricing', httpwww.cooldev.comprices.html, null],
   	      ['On-line registration', httpwww.cooldev.comregistration.html, null],
        ],
	['Team Management', null, null,
              ['Conditions', httpwww.cooldev.comoffshore.html, null],
              ['How to', httpwww.cooldev.comoffshore_how.html, null],
              ['Portfolio', httpwww.cooldev.comportfolio.html, null],
        ],
	['Lead Management', null, null,
              ['Lead Tracker', httpwww.cooldev.comcgi_binguestbook.cgitype=form, null],
              ['Import New Leads', httpwww.cooldev.comsupport.html, null],
              ['Export by Query', httpwww.cooldev.comsupport.html, null],
    	],
	['DNC List Management', null, null,
              ['Federal Import', httpjavascript.cooldev.com, _blank],
              ['State Import', httpgalagraphia.cooldev.com, _blank],
              ['Export Federal', httpwww.cooldev.comdelphilinks.html, null],
              ['Export by State', httpwww.cooldev.comdelphilinks.html, null],
              ['Export by Query', httpwww.cooldev.comdelphilinks.html, null],
        ],
];
