document.write('<object ID="musplPla" NAME="musplPla" CLASSID="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" WIDTH="230" HEIGHT="50" CODEBASE="download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0">');
document.write('<PARAM NAME="MOVIE" VALUE="MP3Streamer.swf">');
document.write('<param NAME="PLAY" VALUE="false">');
document.write('<param NAME="LOOP" VALUE="false">');
document.write('<param NAME="QUALITY" VALUE="high">');
document.write('<param NAME="MENU" VALUE="false">');
document.write('<param NAME="WMODE" VALUE="transparent">');
document.write('<embed ID="musplPla" NAME="musplPla" wmode="transparent" SRC="MP3Streamer.swf" WIDTH="230" HEIGHT="50" PLAY="false" LOOP="false" QUALITY="high" MENU="false" TYPE="application/x-shockwave-flash" PLUGINSPAGE="www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">');
document.write('</embed>');
document.write('</object>');
